# Generated by Django 5.0.6 on 2024-06-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
