# Generated by Django 5.0.6 on 2024-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_client_alter_client_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True, verbose_name='имя пользователя'),
        ),
    ]
