# Generated by Django 5.0.6 on 2024-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_client_options_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
    ]
