# Generated by Django 5.0.6 on 2024-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
