# Generated by Django 5.0.6 on 2024-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_client_second_name_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
