# Generated by Django 5.0.6 on 2024-06-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/', verbose_name='Изображение профиля')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='users.client')),
            ],
            options={
                'verbose_name': 'Изображение профиля',
                'verbose_name_plural': 'Изображения профилей',
            },
        ),
    ]
