# Generated by Django 5.0.6 on 2024-06-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/main/img/profile_img', verbose_name='Доступное изображение')),
            ],
            options={
                'verbose_name': 'Доступное изображение',
                'verbose_name_plural': 'Доступные изображения',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.imageoption', verbose_name='Изображение профиля'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
