# Generated by Django 5.0.6 on 2024-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_imageoption_client_profile_image_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество'),
        ),
    ]
