# Generated by Django 5.0.6 on 2024-06-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_description_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание книги'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
