# Generated by Django 5.0.6 on 2024-06-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_author_alter_book_publisher_delete_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
