# Generated by Django 5.0.6 on 2024-06-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_book_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
    ]
