# Generated by Django 5.0.6 on 2024-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_book_options_alter_genre_options_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='library_system\\main\\static\\main\\img', verbose_name='Фото для обложки'),
        ),
    ]
